In [1]:
import torch

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# 정수, index로 많이 쓰임

lt = torch.LongTensor([[1, 2],
                      [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [4]:
## 0과 1을 담는 tensor

bt  = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [6]:
## 크기만 정하고 숫자 랜덤으로 

x = torch.FloatTensor(3, 2)
x

tensor([[4.1722e+21, 1.2780e+22],
        [1.3370e+22, 1.3310e+22],
        [5.1886e-11, 7.1450e+31]])

### NumPy Compatibility

In [7]:
import numpy as np

# Define numpy array
x = np.array([[1, 2],
             [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [8]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


### Tensor Type-casting
- type이 같아야 계산 가능

In [9]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [10]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [11]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

### Get Shape

In [12]:
x = torch.FloatTensor([[[1,2],
                       [3,4]],
                       [[5, 6],
                       [7, 8]],
                       [[9,10],
                       [11, 12]]])

In [15]:
print(x.shape)
print(x.size())

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [16]:
print(x.dim())
print(len(x.size()))

3
3


In [20]:
print(x.size(1))
print(x.shape[1])

2
2


In [21]:
print(x.size(-1))
print(x.size(-1))

2
2


In [23]:
x.shape[0]

3