In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [3]:
torch.cat([x, y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [4]:
torch.cat([x, y], dim=0).shape

torch.Size([4, 2])

In [5]:
torch.cat([x, y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [6]:
torch.cat([x, y], dim=1).shape

torch.Size([2, 4])

In [7]:
x = torch.FloatTensor([1, 3])
y = torch.FloatTensor([2, 4])
z = torch.FloatTensor([5, 6])

In [8]:
torch.stack([x, y, z])

tensor([[1., 3.],
        [2., 4.],
        [5., 6.]])

In [10]:
x

tensor([1., 3.])

In [11]:
x.shape

torch.Size([2])

In [13]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)

tensor([[1., 3.],
        [2., 4.],
        [5., 6.]])

In [12]:
x.unsqueeze(0).shape

torch.Size([1, 2])

In [16]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 5.],
        [3., 4., 6.]])

In [17]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
x

tensor([[0., 1., 2.],
        [2., 1., 0.]])

In [19]:
# 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
#입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [23]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [24]:
x.mul(2.)

tensor([[2., 4.],
        [6., 8.]])

In [25]:
x

tensor([[1., 2.],
        [3., 4.]])

In [26]:
x.mul_(2.)

tensor([[2., 4.],
        [6., 8.]])

In [27]:
x

tensor([[2., 4.],
        [6., 8.]])