In [2]:
import numpy as np

In [3]:
t = np.array([0, 1, 2, 3, 4, 5, 6])
t

array([0, 1, 2, 3, 4, 5, 6])

In [4]:
print('Rank ot:', t.ndim)  
print('Shanpe of t:', t.shape)

Rank ot: 1
Shanpe of t: (7,)


In [5]:
print('t[2:5] t[4:1] = ', t[2:5], t[4:-1])

t[2:5] t[4:1] =  [2 3 4] [4 5]


In [7]:
print('t[:2] t[4:] = ', t[:2], t[4:])

t[:2] t[4:] =  [0 1] [4 5 6]


In [8]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
print(t.ndim)
print(t.shape)

2
(4, 3)


In [10]:
import torch

In [11]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
t

tensor([0., 1., 2., 3., 4., 5., 6.])

In [12]:
print(t.dim())    # rank. 차원
print(t.shape)    # shape
print(t.size())   # shape

1
torch.Size([7])
torch.Size([7])


In [13]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [15]:
t=torch.FloatTensor([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]
                    ])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [16]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [18]:
print(t[:,1]) # 1열의 전체 행
print(t[:,1].size()) 

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [20]:
print(t[:, :-1])  # 전체 행중에서 마지막 열 빼고 가지고 오기

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [22]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [24]:
#Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])  # [3] -> [3, 3]
m1 + m2

tensor([[4., 5.]])

In [25]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])
