In [3]:
import torch
import numpy as np

In [5]:
t = np.array([[[0, 1, 2],
              [3, 4, 5]],
              [[6, 7, 8],
              [9, 10, 11]]])
ft = torch.FloatTensor(t)
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [6]:
ft.shape

torch.Size([2, 2, 3])

In [7]:
ft.view([-1, 3])   # ft라는 텐서를 (?, 3)의 크기로 변경

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [8]:
ft.view([-1, 3]).shape

torch.Size([4, 3])

In [9]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [10]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
ft.squeeze()

tensor([0., 1., 2.])

In [12]:
ft.squeeze().shape

torch.Size([3])

In [13]:
ft = torch.Tensor([0, 1, 2])
ft.shape

torch.Size([3])

In [14]:
# 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다. 
ft.unsqueeze(0)

tensor([[0., 1., 2.]])

In [15]:
ft.unsqueeze(0).shape

torch.Size([1, 3])

In [16]:
ft.view(1, -1)

tensor([[0., 1., 2.]])

In [17]:
ft.view(1, -1).shape

torch.Size([1, 3])

In [18]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [19]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [20]:
lt = torch.LongTensor([1, 2, 3, 4])
lt

tensor([1, 2, 3, 4])

In [21]:
lt.float()

tensor([1., 2., 3., 4.])

In [22]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [23]:
bt.long()

tensor([1, 0, 0, 1])

In [24]:
bt.float()

tensor([1., 0., 0., 1.])