In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [9]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [14]:
# x_data의 속성을 유지
x_ones = torch.ones_like(x_data)
print(f'Ones Tensor: \n {x_ones} \n')

#x_data의 속성을 덮어쓰기
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'Random Tensor: \n {x_rand} \n')

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8180, 0.2618],
        [0.8497, 0.2206]]) 

